# -*- coding: utf-8 -*-
"""Prodigy_InfoTech-Intern-Task1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vXOo15dXNSp7xevnvMNJM1RCz27fZTtP

#Task-01

Create a bar chart or histogram to visualize the distribution of a categorical or continuous variable, such as the distribution of ages or genders in a population.

Dataset Link:https://www.kaggle.com/datasets/iamsouravbanerjee/customer-shopping-trends-dataset/data

#Importing the required Libraries
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

"""#Importing the dataset"""

df = pd.read_csv('/content/shopping_trends.csv')
df

"""Dataset Glossary (Column-wise)

Customer ID - Unique identifier for each customer

Age - Age of the customer

Gender - Gender of the customer (Male/Female)

Item Purchased - The item purchased by the customer

Category - Category of the item purchased

Purchase Amount (USD) - The amount of the purchase in USD

Location - Location where the purchase was made

Size - Size of the purchased item

Color - Color of the purchased item

Season - Season during which the purchase was made

Review Rating - Rating given by the customer for the purchased item

Subscription Status - Indicates if the customer has a subscription (Yes/No)

Shipping Type - Type of shipping chosen by the customer

Discount Applied - Indicates if a discount was applied to the purchase (Yes/No)

Promo Code Used - Indicates if a promo code was used for the purchase (Yes/No)

Previous Purchases - Number of previous purchases made by the customer

Payment Method - Customer's most preferred payment method

Frequency of Purchases - Frequency at which the customer makes purchases (e.g., Weekly, Fortnightly, Monthly)
"""

df.head(5)

df.shape

df.info()

df.describe()

df.isnull().sum()

"""#Histogram of Continuous Variable"""

plt.figure(figsize=(20, 6))
sns.histplot(data=df, x='Age', kde=True, color='blue')
plt.title('Customer Age Distribution', size=16)
plt.xlabel('Customer Age')
plt.ylabel('Customer Count')
plt.show()

"""#BarPlot of Categorical Variable"""

plt.figure(figsize=(20, 6))
sns.countplot(data=df, x='Gender', color='blue')
plt.title('Customer Gender Distribution', size=16)
plt.xlabel('Customer Gender')
plt.ylabel('Gender Count')
plt.show()